Repository AY2324S2-CS2103-F15-1/tp, pull requests merged in 2024-04, with the labels that each got.

#161 Update quantifier in command format definition
  docs/UserGuide.md
Labels: type.documentation, priority.medium

#160 Refactor find command to get present prefix
  src/main/java/seedu/findvisor/logic/commands/FindCommand.java
  src/main/java/seedu/findvisor/logic/parser/FindCommandParser.java
  src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java
Labels: priority.high, type.refactor

#169 Allow users to find persons by remark and meeting remark
  src/main/java/seedu/findvisor/logic/commands/FindCommand.java
  src/main/java/seedu/findvisor/logic/parser/CliSyntax.java
  src/main/java/seedu/findvisor/logic/parser/FindCommandParser.java
  src/main/java/seedu/findvisor/model/person/PersonAddressPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonEmailPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonMeetingPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonMeetingRemarkPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonNamePredicate.java
  src/main/java/seedu/findvisor/model/person/PersonPhonePredicate.java
  src/main/java/seedu/findvisor/model/person/PersonRemarkPredicate.java
  src/main/java/seedu/findvisor/model/tag/PersonTagsPredicate.java
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/findvisor/model/person/PersonEmailPredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonMeetingRemarkPredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonRemarkPredicateTest.java
Labels: type.feature, priority.high

#174 Update find command description in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#163 Safe string validation for meeting remark
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/logic/parser/ParserUtil.java
  src/main/java/seedu/findvisor/logic/parser/RescheduleCommandParser.java
  src/main/java/seedu/findvisor/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/test/java/seedu/findvisor/commons/util/DateTimeUtilTest.java
  src/test/java/seedu/findvisor/logic/parser/ParserUtilTest.java
  src/test/java/seedu/findvisor/model/person/MeetingTest.java
Labels: type.bug, priority.high

#162 Update remark documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.high

#177 Update ug with add tag command
  docs/UserGuide.md
Labels: type.documentation, priority.high

#117 Implement delete tag command
  src/main/java/seedu/findvisor/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/findvisor/logic/parser/AddressBookParser.java
  src/main/java/seedu/findvisor/logic/parser/DeleteTagCommandParser.java
  src/test/java/seedu/findvisor/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/DeleteTagCommandParserTest.java
Labels: type.feature, priority.high

#172 Add descriptions of commands to Help Window
  src/main/java/seedu/findvisor/ui/HelpWindow.java
Labels: type.feature, priority.high

#175 Add UG and DG docs for Reschedule Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.high

#183 Update use cases
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#181 Add add tags use case to and correct some sequence diagram errors
  docs/DeveloperGuide.md
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/images/AddTagSequenceDiagram.svg
Labels: type.documentation, priority.high

#186 Fix table formatting in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#173 Update DG and UG for Delete Tag Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.high

#182 Fix UML diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteTagSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram-Logic.puml
  docs/diagrams/FindMeetingDateSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/RemarkSequenceDiagram-Logic.puml
  docs/diagrams/ScheduleMeetingSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/images/DeleteSequenceDiagram.svg
  docs/images/DeleteTagSequenceDiagram.svg
  docs/images/EditSequenceDiagram-Logic.svg
  docs/images/FindMeetingDateSequenceDiagram.svg
  docs/images/FindSequenceDiagram.svg
  docs/images/RemarkSequenceDiagram-Logic.svg
  docs/images/ScheduleMeetingSequenceDiagram.svg
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Logic.svg
  docs/images/UndoSequenceDiagram-Model.png
  docs/images/UndoSequenceDiagram-Model.svg
Labels: type.documentation, priority.high

#187 Add use case for searching persons
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#185 Increase font size and move button to the top
  src/main/java/seedu/findvisor/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.high, type.ui

#192 Update product screenshots
  copyright.txt
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: type.documentation, priority.high

#193 Refactor message usage to match UG
  src/main/java/seedu/findvisor/logic/commands/AddCommand.java
  src/main/java/seedu/findvisor/logic/commands/AddTagCommand.java
  src/main/java/seedu/findvisor/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/findvisor/logic/commands/EditCommand.java
  src/main/java/seedu/findvisor/logic/commands/FindCommand.java
  src/main/java/seedu/findvisor/logic/commands/RescheduleCommand.java
  src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java
Labels: priority.high, type.refactor

#202 Update help window to display table
  src/main/java/seedu/findvisor/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.high, type.enhancement

#268 Set resolver style to strict to reject all invalid values
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/test/java/seedu/findvisor/commons/util/DateTimeUtilTest.java
Labels: type.bug, priority.high

#269 Update description for find result for tags
  docs/UserGuide.md
Labels: type.documentation, priority.high

#271 Update help window
  src/main/java/seedu/findvisor/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.bug, priority.high

#270 Update remark value format to be optional
  docs/UserGuide.md
Labels: type.documentation, priority.high

#274 Update UG to specify non-blank constraint
  docs/UserGuide.md
Labels: type.documentation, priority.high

#275 Update clear command in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#277 Revert file saved file name in UG to addressbook.json
  docs/UserGuide.md
Labels: type.documentation, priority.high

#279 Update name constraint in ug to alphanumeric
  docs/UserGuide.md
Labels: type.documentation, priority.high

#278 Standardize blank parameter specification
  docs/UserGuide.md
Labels: type.documentation, priority.high

#281 Add planned enhancements for remarks and address
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#273 Add clear definition of target user in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#286 Update UG for deletion
  docs/UserGuide.md
Labels: type.documentation, priority.high

#284 State we do not officially support directly editing the data file
  docs/UserGuide.md
Labels: type.documentation, priority.high

#289 Remove unused method in StringUtil.java
  src/main/java/seedu/findvisor/commons/util/StringUtil.java
  src/test/java/seedu/findvisor/commons/util/StringUtilTest.java
Labels: priority.medium, type.refactor

#294 Add regression test for IllegalArgumentException being thrown
  src/test/java/seedu/findvisor/logic/parser/RescheduleCommandParserTest.java
Labels: priority.medium, type.test

#296 Remove proposed changes from DG
  docs/DeveloperGuide.md
Labels: type.documentation, priority.medium

#287 Update dg planned enhancement section
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#276 Add date and datetime input enhancement
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#299 Add section explaining UI interactions in UG
  docs/UserGuide.md
  docs/images/Ui-Annotated.png
  docs/images/Ui-Failure.png
  docs/images/Ui-Success.png
Labels: type.documentation, priority.high

#292 Add planned enhancement for overlapping meetings
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#293 Refactor meeting fields to private
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/main/java/seedu/findvisor/model/person/PersonMeetingPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonTodayMeetingsPredicate.java
  src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/findvisor/logic/MessagesTest.java
  src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/findvisor/logic/parser/RescheduleCommandParserTest.java
  src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java
Labels: priority.medium, type.refactor

#305 Revert date format in find error message
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
Labels: type.bug, priority.high

#310 Fix use cases and user stories
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#311 Update user guide
  docs/UserGuide.md
Labels: type.documentation, priority.medium

#313 Update target user profile and value proposition
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#319 Update DG links to point to team repo
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#316 Add undo redo enhancement
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#314 Update manual testing appendix
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#317 Add more test appendix
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#323 Include addtag and deletetag test cases in DG
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#318 Update UG to specify behaviour of UI
  docs/UserGuide.md
Labels: type.documentation, priority.high

#324 Add definitions of client, contact and person
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.high

#315 Add test cases for list, edit and find in DG
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#325 Update description of FINDvisor in index.md
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: type.documentation, priority.high

#329 Update UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#330 Rephrase schedule and unschedule test cases
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#331 Fix formatting errors in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#332 Update DG
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#334 Fix grammar error in Features
  docs/UserGuide.md
Labels: type.documentation, priority.low
