Repository AY2324S2-CS2103-F15-1/tp, pull requests merged in 2024-03, with the labels that each got.

#51 Update NFRs in DG to match TP constraints exhaustively
  docs/DeveloperGuide.md
Labels: type.documentation

#61 Modify AboutUs
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/yuzizhen.png
Labels: type.documentation

#66 Update User Guide for Edit command
  docs/UserGuide.md
Labels: type.documentation

#71 Update isSamePerson
  src/main/java/seedu/findvisor/model/person/Person.java
  src/test/java/seedu/findvisor/model/person/PersonTest.java
Labels: type.enhancement

#2 Add `schedule` command to schedule meetings
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java
  src/main/java/seedu/findvisor/logic/parser/AddressBookParser.java
  src/main/java/seedu/findvisor/logic/parser/CliSyntax.java
  src/main/java/seedu/findvisor/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/main/java/seedu/findvisor/model/person/Person.java
  src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/findvisor/storage/JsonAdaptedPerson.java
  src/main/java/seedu/findvisor/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/findvisor/commons/util/DateTimeUtilTest.java
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/findvisor/model/person/MeetingTest.java
  src/test/java/seedu/findvisor/model/person/PersonTest.java
  src/test/java/seedu/findvisor/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/findvisor/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/findvisor/testutil/PersonBuilder.java
Labels: type.feature

#72 Add unschedule Command
  src/main/java/seedu/findvisor/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/findvisor/logic/parser/AddressBookParser.java
  src/main/java/seedu/findvisor/logic/parser/UnscheduleCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/findvisor/logic/commands/UnscheduleCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/findvisor/logic/parser/UnscheduleCommandParserTest.java
  src/test/java/seedu/findvisor/testutil/TypicalPersons.java
Labels: type.feature

#83 Update UG to match v1.2 features
  docs/UserGuide.md
  docs/_includes/custom-head.html
  docs/assets/favicon.ico
Labels: type.documentation

#86 Fix javadoc for Meeting class
  src/main/java/seedu/findvisor/model/person/Meeting.java
Labels: type.documentation

#89 Update command summary in UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#73 Update phone and name parsing logic
  src/main/java/seedu/findvisor/logic/parser/ParserUtil.java
  src/main/java/seedu/findvisor/model/person/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/findvisor/logic/parser/ParserUtilTest.java
  src/test/java/seedu/findvisor/model/person/PhoneTest.java
  src/test/java/seedu/findvisor/testutil/TypicalPersons.java
Labels: type.enhancement

#87 Add missing meeting fields for json test files
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
Labels: type.bug

#96 bugfix for edit not copyign meeting details over
  src/main/java/seedu/findvisor/logic/commands/EditCommand.java
  src/test/java/seedu/findvisor/logic/commands/EditCommandTest.java
Labels: type.bug, priority.high

#101 Rename JAR filename to findvisor.jar
  build.gradle
Labels: priority.high, type.refactor

#104 Update app icon and include acknowledgement
  docs/index.md
  src/main/resources/images/address_book_32.png
  src/main/resources/images/findvisor.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/findvisor/commons/util/AppUtilTest.java
Labels: type.ui

#103 Update title bar text to FINDvisor
  src/main/java/seedu/findvisor/MainApp.java
  src/main/resources/view/MainWindow.fxml
Labels: type.ui

#106 Fix icon path in UiManager
  copyright.txt
  src/main/java/seedu/findvisor/ui/UiManager.java
Labels: type.bug

#109 Update DG to use correct package name
  docs/DeveloperGuide.md
Labels: type.documentation

#112 Update Storage class diagram
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.documentation

#113 Add Meeting class to Model class diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.documentation

#116 Enable assertions in `build.gradle`
  build.gradle
Labels: priority.high, type.test

#97 Feature: Meeting's can store remark
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java
  src/main/java/seedu/findvisor/logic/parser/CliSyntax.java
  src/main/java/seedu/findvisor/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/main/java/seedu/findvisor/storage/JsonAdaptedMeeting.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/findvisor/logic/MessagesTest.java
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/findvisor/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/findvisor/model/person/MeetingTest.java
  src/test/java/seedu/findvisor/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/findvisor/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/findvisor/testutil/TypicalPersons.java
Labels: type.feature

#139 Add find feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.svg
Labels: type.documentation

#141 Add address searching feature to find command
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/FindCommand.java
  src/main/java/seedu/findvisor/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/findvisor/logic/parser/FindCommandParser.java
  src/main/java/seedu/findvisor/model/person/AddressContainsKeywordPredicate.java
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/findvisor/model/person/AddressContainsKeywordPredicateTest.java
Labels: type.feature, priority.high

#145 Add search meeting date feature to find command
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/FindCommand.java
  src/main/java/seedu/findvisor/logic/parser/CliSyntax.java
  src/main/java/seedu/findvisor/logic/parser/FindCommandParser.java
  src/main/java/seedu/findvisor/logic/parser/ParserUtil.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/main/java/seedu/findvisor/model/person/PersonAddressPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonEmailPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonMeetingPredicate.java
  src/main/java/seedu/findvisor/model/person/PersonNamePredicate.java
  src/main/java/seedu/findvisor/model/person/PersonPhonePredicate.java
  src/main/java/seedu/findvisor/model/tag/PersonTagsPredicate.java
  src/test/java/seedu/findvisor/commons/util/DateTimeUtilTest.java
  src/test/java/seedu/findvisor/logic/commands/CommandTestUtil.java
  src/test/java/seedu/findvisor/logic/commands/FindCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/findvisor/logic/parser/ParserUtilTest.java
  src/test/java/seedu/findvisor/model/person/PersonAddressPredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonEmailPredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonMeetingPredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonNamePredicateTest.java
  src/test/java/seedu/findvisor/model/person/PersonPhonePredicateTest.java
  src/test/java/seedu/findvisor/model/tag/PersonTagsPredicateTest.java
Labels: type.feature, priority.high

#148 Add meeting panel
  src/main/java/seedu/findvisor/logic/Logic.java
  src/main/java/seedu/findvisor/logic/LogicManager.java
  src/main/java/seedu/findvisor/model/Model.java
  src/main/java/seedu/findvisor/model/ModelManager.java
  src/main/java/seedu/findvisor/model/person/PersonTodayMeetingsPredicate.java
  src/main/java/seedu/findvisor/model/util/SampleDataUtil.java
  src/main/java/seedu/findvisor/ui/MainWindow.java
  src/main/java/seedu/findvisor/ui/MeetingCard.java
  src/main/java/seedu/findvisor/ui/MeetingListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/test/java/seedu/findvisor/logic/LogicManagerTest.java
  src/test/java/seedu/findvisor/logic/commands/AddCommandTest.java
  src/test/java/seedu/findvisor/model/ModelManagerTest.java
  src/test/java/seedu/findvisor/model/person/PersonTodayMeetingsPredicateTest.java
Labels: priority.high, type.ui

#147 New `reschedule` command
  src/main/java/seedu/findvisor/commons/util/DateTimeUtil.java
  src/main/java/seedu/findvisor/logic/Messages.java
  src/main/java/seedu/findvisor/logic/commands/EditCommand.java
  src/main/java/seedu/findvisor/logic/commands/RescheduleCommand.java
  src/main/java/seedu/findvisor/logic/commands/ScheduleCommand.java
  src/main/java/seedu/findvisor/logic/parser/AddressBookParser.java
  src/main/java/seedu/findvisor/logic/parser/EditCommandParser.java
  src/main/java/seedu/findvisor/logic/parser/RescheduleCommandParser.java
  src/main/java/seedu/findvisor/model/person/Meeting.java
  src/test/java/seedu/findvisor/logic/commands/EditMeetingDescriptorTest.java
  src/test/java/seedu/findvisor/logic/commands/RescheduleCommandTest.java
  src/test/java/seedu/findvisor/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/findvisor/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/findvisor/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/findvisor/logic/parser/RescheduleCommandParserTest.java
  src/test/java/seedu/findvisor/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/findvisor/testutil/MeetingBuilder.java
  src/test/java/seedu/findvisor/testutil/MeetingUtil.java
Labels: type.feature, priority.high

#158 Update validation regex for addresses
  src/main/java/seedu/findvisor/model/person/Address.java
  src/test/java/seedu/findvisor/model/person/AddressTest.java
Labels: type.bug, priority.high
