Repository AY2324S2-CS2103-F15-1/tp, pull requests merged in 2024-02, with the labels that each got.

#35 Update Jekyll site-wide settings
  docs/_config.yml
  docs/_data/projects.yml
  docs/_includes/custom-head.html
  docs/_sass/minima/_base.scss
  docs/favicon.ico
  docs/index.md
Labels: type.documentation

#34 Update UG command formats
  docs/UserGuide.md
Labels: type.documentation

#40 Update AboutUs page
  docs/AboutUs.md
  docs/images/javiery3889.png
  docs/team/johndoe.md
Labels: type.documentation

#43 Update DG
  docs/DeveloperGuide.md
Labels: type.documentation

#42 Add input formats to UG
  docs/UserGuide.md
Labels: type.documentation

#54 Fix alert box for user guide
  docs/UserGuide.md
Labels: type.bug

#55 Update target user and user stories in DG
  docs/DeveloperGuide.md
Labels: type.documentation

#46 Add docs for `schedule` and `unschedule` command
  docs/UserGuide.md
Labels: type.documentation

#48 Add use case for scheduling meeting with a new person
  docs/DeveloperGuide.md
Labels: type.documentation

#52 Update `find` and `help` commands in user guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.documentation

#49 Update individual about us entry
  docs/AboutUs.md
  docs/images/arixeyeion.png
Labels: type.documentation

#58 Add exit action to command summary table
  docs/UserGuide.md
Labels: type.documentation, priority.low
